# Generated by Django 5.1.7 on 2026-05-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_template_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trigger_type',
            field=models.CharField(choices=[('renewal_remind', 'Renewal Reminder'), ('renewal_confirm', 'Renewal Confirmed'), ('enrollment', 'New Enrollment'), ('expiry', 'Membership Expired'), ('manual', 'Manual'), ('enquiry_welcome', 'Enquiry Welcome'), ('enquiry_followup', 'Enquiry Follow-up'), ('absent', 'Member Absent'), ('staff_absent', 'Staff Absent'), ('new_plan', 'New Plan Announcement'), ('diet_reminder', 'Diet Reminder'), ('pending_payment_member', 'Pending Payment Reminder'), ('pending_payment_admin', 'Pending Payment Summary (Admin)')], default='manual', max_length=30),
        ),
    ]
