# Generated by Django 5.1.7 on 2026-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_merge_20260418_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpayment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
