# Generated by Django 5.1.7 on 2026-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_memberpayment_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gym_member_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
