# Generated by Django 5.1.7 on 2026-05-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_member_gym_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
